services:
  gitbox:
    image: semanticrelease/docker-gitbox:latest@sha256:c0c2a595740e070c4b4dbe5bcd389da21e670008958967e74cd1a9ba8bcb3afa
    tty: true
    stdin_open: true
    ports:
      - "80"

  npm-registry:
    image: verdaccio/verdaccio:6.9.0@sha256:11e75353c8363650cbf43adf8594b2cd633be6f191056c6e08ba6ff4b1398f62
    ports:
      - "4873"
    volumes:
      - ./config.yaml:/verdaccio/conf/config.yaml:ro

  mockserver:
    image: mockserver/mockserver:7.5.0@sha256:a268c84e2e3a8a0682b9771f37ed0f201ea9ec921ef05b945be80e52eedf6f55
    ports:
      - "1080"
