name: Bug Report
description: Something not working as expected
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Current behavior
      description: Describe how the issue manifests.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what the desired behavior would be.
    validations:
      required: true

  - type: input
    attributes:
      label: "`semantic-release` version"
      description: |
        The version executed in your pipeline, printed in the first line of output.
        If not already using the latest version, please try upgrading to the latest version and refreshing your lockfile to see if the issue persists.
        We will likely ask you to take these steps as the first support steps if you haven't already.
    validations:
      required: true

  - type: input
    attributes:
      label: CI environment
      description: CI service name.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugins used
      description: List `semantic-release` plugin used, if any.
    validations:
      required: false

  - type: textarea
    attributes:
      label: "`semantic-release` configuration"
      description: |
        Link to the configuration in your repository or relevant part of the `semantic-release` config.
        When including configuration directly, please format with triple backticks (```) to ensure it is readable.
    validations:
      required: true

  - type: textarea
    attributes:
      label: CI logs
      description: |
        Link to your CI logs or `semantic-release` logs when executed with the debug flag enabled.
        When including logs directly, please format with triple backticks (```) to ensure it is readable.
    validations:
      required: true
