branches:
  only:
    - master
    - next
    - beta
    - /^\d+\.(\d+|x)(\.x)?$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      install:
        - travis_retry npm install
      script:
        - npm run semantic-release
